### ISSUE TITLE
Ansible Error - ansible.builtin.command

### ISSUE THREAD

**Issue by gpxlnx** [fhemberger/nomad-demo#13]
When I try to run make up I get an ansible error.

Sorry but I don't know much about Ansible.

Any suggestion?

Thank you and congratulations for the work.

=> loadbalancer: Running provisioner: ansible (ansible)...
    loadbalancer: Running ansible-playbook...
ERROR! this task 'ansible.builtin.command' has extra params, which is only allowed in the following modules: win_shell, add_host, include_role, group_by, include, raw, win_command, import_role, meta, command, include_vars, include_tasks, shell, set_fact, import_tasks, script

The error appears to be in '/home/gxavier/nomad-demo/roles/syslog-ng/tasks/main.yml': line 8, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: De-armor GPG key # noqa no-changed-when
  ^ here
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by fhemberger** [comment]
Hmm, this is odd … can you tell me, which version of Ansible you are using?
Please post the entire output of `ansible --version`, thanks!

This seems to be a bug in Ansible versions <= 2.10:
https://github.com/ansible/ansible/pull/71824

**Comment by gpxlnx** [comment]
I'm sorry, I'm not see this issue. 

Using Ansible 2.10 the script ran normally.

Thanks.

**Comment by fhemberger** [comment]
Thanks, I'll add the required Ansible version to the docs. Good catch!
